library(sigminer)
library(maftools)
#maffile <- "../TCGA.merge.somatic.snv.maf.gz"
#sdata <- read.maf(maffile)
#mt_tally_all <- sig_tally(sdata,ref_genome = "BSgenome.Hsapiens.UCSC.hg38",use_syn = TRUE,mode="ALL", add_trans_bias = TRUE)
#save(mt_tally_all, file="tcga.sigminer.RData")
load("tcga.sigminer.RData")
write.table(mt_tally_all$APOBEC_scores, file="tcga.APOBEC_scores.txt",sep="\t",quote=F,row.names=F)
write.table(mt_tally_all$SBS_96, file="tcga.SBS_96.txt",sep="\t",quote=F,row.names=T)
write.table(mt_tally_all$ID_83, file="tcga.ID_83.txt",sep="\t",quote=F,row.names=T)
write.table(mt_tally_all$DBS_78, file="tcga.DBS_78.txt",sep="\t",quote=F,row.names=T)
pdf(file="show_catalogue.tcga.pdf",height=4,width=10)
show_catalogue(t(mt_tally_all$SBS_96), mode="SBS", style = "cosmic", x_label_angle = 90, y_tr = function(x) x / sum(mt_tally_all$SBS_96))
show_catalogue(t(mt_tally_all$ID_83), mode="ID", style = "cosmic", x_label_angle = 90, y_tr = function(x) x / sum(mt_tally_all$ID_83))
show_catalogue(t(mt_tally_all$DBS_78), mode="DBS", style = "cosmic", x_label_angle = 90, y_tr = function(x) x / sum(mt_tally_all$DBS_78))
dev.off()

sbs_sig_fit <- sig_fit(t(mt_tally_all$SBS_96),sig_index="ALL", sig_db="SBS", mode="SBS", return_class = "data.table",rel_threshold = 0.05,type="relative")
write.table(sbs_sig_fit, file="tcga.sbs_sig_fit.txt",sep="\t",quote=F,row.names=F)
id_sig_fit <- sig_fit(t(mt_tally_all$ID_83),sig_index="ALL", sig_db="ID", mode="ID", return_class = "data.table", rel_threshold = 0.05,type="relative")
write.table(id_sig_fit, file="tcga.id_sig_fit.txt",sep="\t",quote=F,row.names=F)
dbs_sig_fit <- sig_fit(t(mt_tally_all$DBS_78),sig_index="ALL", sig_db="DBS", mode="DBS", return_class = "data.table", rel_threshold = 0.05,type="relative")
write.table(dbs_sig_fit, file="tcga.dbs_sig_fit.txt",sep="\t",quote=F,row.names=F)

#perl	merge.cancertype.tcga.pl

sbs <- read.table("tcga.cancertype.SBS_96.txt")
id <- read.table("tcga.cancertype.ID_83.txt")
dbs <- read.table("tcga.cancertype.DBS_78.txt")
colnames(sbs) <- colnames(mt_tally_all$SBS_96)
colnames(id) <- colnames(mt_tally_all$ID_83)
colnames(dbs) <- colnames(mt_tally_all$DBS_78)

sbs_sig_fit2 <- sig_fit(t(sbs),sig_index="ALL", sig_db="SBS", mode="SBS", return_class = "data.table", rel_threshold = 0.05,type="relative")
write.table(sbs_sig_fit2, file="tcga.cancertype.sbs_sig_fit.txt",sep="\t",quote=F,row.names=F)
id_sig_fit2 <- sig_fit(t(id),sig_index="ALL", sig_db="ID", mode="ID", return_class = "data.table", rel_threshold = 0.05,type="relative")
write.table(id_sig_fit2, file="tcga.cancertype.id_sig_fit.txt",sep="\t",quote=F,row.names=F)
dbs_sig_fit2 <- sig_fit(t(dbs),sig_index="ALL", sig_db="DBS", mode="DBS", return_class = "data.table", rel_threshold = 0.05,type="relative")
write.table(dbs_sig_fit2, file="tcga.cancertype.dbs_sig_fit.txt",sep="\t",quote=F,row.names=F)

